IAM Permissions

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -34,33 +34,38 @@ jobs:
         - name: Setup Terraform with specified version on the runner
           uses: hashicorp/setup-terraform@v3
 
-        - name: Terraform Init
-          id: init
-          #run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"
-          run: terraform init
+        # - name: Terraform Init
+        #   id: init
+        #   #run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"
+        #   run: terraform init
 
-        - name: Terraform Format
-          id: fmt
-          run: terraform fmt -check
-          continue-on-error: true 
+        # - name: Terraform Format
+        #   id: fmt
+        #   run: terraform fmt -check
+        #   continue-on-error: true 
 
-        - name: Terraform Validate
-          id: validate
-          run: terraform validate
+        # - name: Terraform Validate
+        #   id: validate
+        #   run: terraform validate
 
-        - name: Terraform Plan
-          id: plan
-          run: terraform plan -no-color -input=false -out planfile
-          continue-on-error: true 
+        # - name: Terraform Plan
+        #   id: plan
+        #   run: terraform plan -no-color -input=false -out planfile
+        #   continue-on-error: true 
 
-        - name: Terraform Plan Status 
-          if: steps.plan.outcome == 'failure'
-          run: exit 1
+        # - name: Terraform Plan Status 
+        #   if: steps.plan.outcome == 'failure'
+        #   run: exit 1
 
-        - name: Terraform Apply
-          id: apply
+        # - name: Terraform Apply
+        #   id: apply
+        #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+        #   run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+
+        - name: Terraform Destroy
+          id: destroy
           if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-          run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+          run: terraform destroy -auto-approve -input=false -parallelism=1 planfile
 
 
 
